Prediction

In [111]:
import torch
import numpy as np

In [112]:
w=torch.tensor([2.0],requires_grad=True)
b=torch.tensor([-1.0],requires_grad=True)

In [113]:
def forward(x):
    yhat=w*x+b
    return yhat
x = torch.tensor([[1.0],[3.0]])
yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.],
        [5.]], grad_fn=<AddBackward0>)


In [114]:
from torch.nn import Linear

In [115]:



torch.manual_seed(1)
lr=torch.nn.Linear(in_features=1, out_features=1,bias=True)
print(list(lr.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [116]:
lr.state_dict()

OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])

In [117]:
print(x)
yhat=lr(x)

tensor([[1.],
        [3.]])


In [118]:
# Practice: Use the linear regression model object lr to make the prediction.

x = torch.tensor([[1.0],[2.0],[3.0]])
yhat=lr(x)
yhat

tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<AddmmBackward0>)

In [119]:
from torch import nn

In [120]:
class LR(nn.Module):
    def __init__(self,input_size,output_size):
        super().__init__()
        self.linear=nn.Linear(input_size,output_size)
    def forward(self,x):
        out=self.linear(x)
        return out

In [121]:
torch.manual_seed(1)
lr1=LR(1,1)
lr1.parameters()
lr1.linear


Linear(in_features=1, out_features=1, bias=True)

In [128]:


x=torch.tensor([1.0])
yhat=lr1(x)
print(list(lr1.parameters()))
print(yhat)

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
tensor([0.0739], grad_fn=<AddBackward0>)


In [130]:

yhat = lr(x)
print("The prediction: ", yhat)

The prediction:  tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward0>)


In [ ]:
for epoch in range(10):
    