In [37]:
import torch
from torch.utils.data import Dataset,DataLoader,SequentialSampler,RandomSampler,default_collate,WeightedRandomSampler,get_worker_info,BatchSampler
import numpy as np

In [41]:
class TestDataset(Dataset):
    def __init__(self) -> None:
        super().__init__()
        pass
    def __getitem__(self, index):
        return index, index*10

    def __len__(self):
        return 100


In [43]:
dataset_obj = TestDataset()

In [ ]:
for data in datase

In [38]:
class sample_dataset(Dataset):
    def __init__(self,length=5):
        self.x=torch.arange(-2,3,requires_grad=False).view(-1,1)
        # self.x=np.arange(-5,5,1).reshape(1,10)
        self.y=10*self.x
        self.length=length
        print(self.x)
    def __getitem__(self,index):
        # 2*list([1,2,3,4])
        sample=self.x[index],self.y[index]
        return sample
    def __len__(self):
        return self.length


datasets=sample_dataset()
print(len(datasets))

tensor([[-2],
        [-1],
        [ 0],
        [ 1],
        [ 2]])
5


In [39]:
for data in datasets:
    print(data)

(tensor([-2]), tensor([-20]))
(tensor([-1]), tensor([-10]))
(tensor([0]), tensor([0]))
(tensor([1]), tensor([10]))
(tensor([2]), tensor([20]))


In [29]:
# samp=SequentialSampler()


train_load=DataLoader(datasets,batch_size=2,sampler=SequentialSampler(datasets))
# default_collate(list(train_load))
for i in train_load:
    print(i)


[tensor([[-2],
        [-1]]), tensor([[-20],
        [-10]])]
[tensor([[0],
        [1]]), tensor([[ 0],
        [10]])]
[tensor([[2]]), tensor([[20]])]


In [30]:
wrepl=list(WeightedRandomSampler([0.1, 0.9, 0.4, 0.7, 3.0, 0.6], 5, replacement=True))
print(wrepl)
worpl=list(WeightedRandomSampler([0.9, 0.4, 0.05, 0.2, 0.3, 0.1], 5, replacement=False))
print(worpl)

[4, 4, 2, 3, 4]
[5, 1, 0, 4, 2]


In [31]:
# dataset=np.loadtxt("heart.csv",delimiter=",",dtype=np.float32,skiprows=1)
# dataset.shape

In [32]:
class sample_datasets(Dataset):
    def __init__(self):
        csv=np.loadtxt("heart.csv",delimiter=",",dtype=np.float32,skiprows=1)
        self.x=torch.from_numpy(csv[:,:12])
        self.y=torch.from_numpy(csv[:,12])
        self.z=torch.from_numpy(csv[:,13])
        self.len=csv.shape[0]
    def __getitem__(self, index):
        return(self.x[index],self.y[index],self.z[index])
    def __len__(self):
        return(self.len)
dataset=sample_datasets()
len(dataset)
for i in range(len(dataset)):
    print(dataset[i])
    print(i)

In [33]:

data_load=DataLoader(dataset=dataset,sampler=SequentialSampler(dataset),batch_size=2,drop_last=True)

for i in data_load:
    print(i)

[tensor([[ 63.0000,   1.0000,   3.0000, 145.0000, 233.0000,   1.0000,   0.0000,
         150.0000,   0.0000,   2.3000,   0.0000,   0.0000],
        [ 37.0000,   1.0000,   2.0000, 130.0000, 250.0000,   0.0000,   1.0000,
         187.0000,   0.0000,   3.5000,   0.0000,   0.0000]]), tensor([1., 2.]), tensor([1., 1.])]
[tensor([[ 41.0000,   0.0000,   1.0000, 130.0000, 204.0000,   0.0000,   0.0000,
         172.0000,   0.0000,   1.4000,   2.0000,   0.0000],
        [ 56.0000,   1.0000,   1.0000, 120.0000, 236.0000,   0.0000,   1.0000,
         178.0000,   0.0000,   0.8000,   2.0000,   0.0000]]), tensor([2., 2.]), tensor([1., 1.])]
[tensor([[ 57.0000,   0.0000,   0.0000, 120.0000, 354.0000,   0.0000,   1.0000,
         163.0000,   1.0000,   0.6000,   2.0000,   0.0000],
        [ 57.0000,   1.0000,   0.0000, 140.0000, 192.0000,   0.0000,   1.0000,
         148.0000,   0.0000,   0.4000,   1.0000,   0.0000]]), tensor([2., 1.]), tensor([1., 1.])]
[tensor([[ 56.0000,   0.0000,   1.0000, 140.0000,

In [34]:
train_size=int(0.8*len(dataset))
test_size=int(0.2*len(dataset))
train_set=dataset[:train_size]
test_set=dataset[train_size:]

# print(train_set)

data_load=DataLoader(dataset=dataset,batch_sampler=BatchSampler(RandomSampler(dataset),batch_size=2,drop_last=True))
# data_load.get_worker_info()

print(len(data_load))

for i in data_load:
    print(i)

151
[tensor([[ 35.,   1.,   0., 126., 282.,   0.,   0., 156.,   1.,   0.,   2.,   0.],
        [ 54.,   0.,   2., 160., 201.,   0.,   1., 163.,   0.,   0.,   2.,   1.]]), tensor([3., 2.]), tensor([0., 1.])]
[tensor([[ 67.0000,   1.0000,   0.0000, 160.0000, 286.0000,   0.0000,   0.0000,
         108.0000,   1.0000,   1.5000,   1.0000,   3.0000],
        [ 63.0000,   0.0000,   0.0000, 150.0000, 407.0000,   0.0000,   0.0000,
         154.0000,   0.0000,   4.0000,   1.0000,   3.0000]]), tensor([2., 3.]), tensor([0., 0.])]
[tensor([[ 41.,   0.,   1., 126., 306.,   0.,   1., 163.,   0.,   0.,   2.,   0.],
        [ 41.,   1.,   2., 112., 250.,   0.,   1., 179.,   0.,   0.,   2.,   0.]]), tensor([2., 2.]), tensor([1., 1.])]
[tensor([[ 65.0000,   1.0000,   0.0000, 120.0000, 177.0000,   0.0000,   1.0000,
         140.0000,   0.0000,   0.4000,   2.0000,   0.0000],
        [ 50.0000,   0.0000,   0.0000, 110.0000, 254.0000,   0.0000,   0.0000,
         159.0000,   0.0000,   0.0000,   2.0000,   0.0

In [35]:
import time
start_time=time.time()
# print(start_time*100)
data_load=DataLoader(dataset,batch_size=3,sampler=RandomSampler(dataset))

print((time.time()-start_time)*1000)



0.08249282836914062


In [36]:
start_time=time.time()
# print(start_time*100)
data_load=DataLoader(dataset,batch_size=3,sampler=RandomSampler(dataset),num_workers=5,prefetch_factor=5)

print((time.time()-start_time)*1000)

0.11229515075683594
