In [21]:
import torch
from torch.utils.data import Dataset,DataLoader
import matplotlib.pyplot as plt
from torch.nn import Linear
from torch import optim

In [22]:
class Table_data(Dataset):
    def __init__(self,length=50):
        self.x=torch.arange(-50,50,1).view(-1,1).type(torch.float32)
        self.y=8*torch.arange(-50,50,1).view(-1,1).type(torch.float32)
        self.len=length
    def __getitem__(self,index):
        sample=self.x[index], self.y[index]
        return(sample)
    def __len__(self):
        return self.len


In [23]:
class Temp:
    def __init__(self) -> None:
        self.x = 10
        

In [24]:
temp_obj = Temp()

In [25]:
temp_obj.x

10

In [26]:
full_dataset=Table_data()

In [27]:
full_dataset.x

tensor([[-50.],
        [-49.],
        [-48.],
        [-47.],
        [-46.],
        [-45.],
        [-44.],
        [-43.],
        [-42.],
        [-41.],
        [-40.],
        [-39.],
        [-38.],
        [-37.],
        [-36.],
        [-35.],
        [-34.],
        [-33.],
        [-32.],
        [-31.],
        [-30.],
        [-29.],
        [-28.],
        [-27.],
        [-26.],
        [-25.],
        [-24.],
        [-23.],
        [-22.],
        [-21.],
        [-20.],
        [-19.],
        [-18.],
        [-17.],
        [-16.],
        [-15.],
        [-14.],
        [-13.],
        [-12.],
        [-11.],
        [-10.],
        [ -9.],
        [ -8.],
        [ -7.],
        [ -6.],
        [ -5.],
        [ -4.],
        [ -3.],
        [ -2.],
        [ -1.],
        [  0.],
        [  1.],
        [  2.],
        [  3.],
        [  4.],
        [  5.],
        [  6.],
        [  7.],
        [  8.],
        [  9.],
        [ 10.],
        [ 11.],
        

In [28]:
from torch import nn

In [29]:

class LR(nn.Module):
    def __init__(self,input_size,output_size):
        super().__init__()
        self.linear=nn.Linear(input_size,output_size)
    def forward(self,x):
        out=self.linear(x)
        return out

    

In [30]:
# x=x.type(torch.float32)

# torch.manual_seed(1)
# lr=LR(1,1)
# print(list(lr.parameters()))
# lr(x)


In [31]:
torch.manual_seed(1)
lr=LR(1,1)

train_size = int(0.8 * len(full_dataset))
test_size = int(0.2*len(full_dataset))

train_dataset, test_dataset = torch.utils.data.random_split(full_dataset, [train_size, test_size])
print(train_size,test_size)

# print("Train dataset:::",train_dataset[0:],"Test dataset:::",test_dataset)

print(train_dataset,test_dataset)

trainloader = DataLoader(dataset = train_dataset, batch_size = len(train_dataset))
testloader=  DataLoader(dataset = test_dataset, batch_size=len(test_dataset)   )

criteria=nn.MSELoss()

print(list(trainloader))
# print()

sgd=optim.SGD(lr.parameters(),0.0001)


40 10
<torch.utils.data.dataset.Subset object at 0x7f8b97107cd0> <torch.utils.data.dataset.Subset object at 0x7f8b971075b0>
[[tensor([[-26.],
        [-46.],
        [-17.],
        [-22.],
        [-25.],
        [ -4.],
        [-33.],
        [ -6.],
        [-10.],
        [-45.],
        [-41.],
        [-28.],
        [-29.],
        [-21.],
        [-43.],
        [-40.],
        [-34.],
        [-14.],
        [ -2.],
        [-48.],
        [-35.],
        [-49.],
        [ -5.],
        [-18.],
        [-27.],
        [-23.],
        [-19.],
        [-13.],
        [-16.],
        [-47.],
        [-38.],
        [-20.],
        [-11.],
        [-42.],
        [ -9.],
        [-37.],
        [-31.],
        [-24.],
        [ -3.],
        [-12.]]), tensor([[-208.],
        [-368.],
        [-136.],
        [-176.],
        [-200.],
        [ -32.],
        [-264.],
        [ -48.],
        [ -80.],
        [-360.],
        [-328.],
        [-224.],
        [-232.],
        [-1

In [41]:

print(list(lr.parameters()))


def Table_nn(lr,trainloader,testloader,sgd,criteria):
    train_loss=[]
    test_loss=[]
    for epoch in range(100):
        for x1,y1 in trainloader:
            yhat_train=lr(x1)
            trloss=criteria(yhat_train,y1)
        
            sgd.zero_grad()
            trloss.backward()
        # print(trloss)
            sgd.step()
        train_loss.append(trloss.detach().numpy())

        for x2,y2 in testloader:
            yhat_test=lr(x2)
            tsloss=criteria(yhat_test,y2)
        
        test_loss.append(tsloss.detach().numpy())
    
        # print("epoch {}:: , train_loss {} ::: , test_loss {}".format(epoch,trloss,tsloss))
    return lr,test_loss,train_loss
        
    

[Parameter containing:
tensor([[7.9801]], requires_grad=True), Parameter containing:
tensor([-0.6555], requires_grad=True)]


In [42]:



X=torch.tensor([[5.0]],requires_grad=True)

predicted,test_loss,train_loss=Table_nn(lr,trainloader,testloader,sgd,criteria)
print(predicted(X))
print(test_loss,train_loss)
print(len(test_loss),len(train_loss))

tensor([[39.2486]], grad_fn=<AddmmBackward0>)
[array(0.12291368, dtype=float32), array(0.1229014, dtype=float32), array(0.12288852, dtype=float32), array(0.12287865, dtype=float32), array(0.12286635, dtype=float32), array(0.12285572, dtype=float32), array(0.12284429, dtype=float32), array(0.12283441, dtype=float32), array(0.12282394, dtype=float32), array(0.1228113, dtype=float32), array(0.12280061, dtype=float32), array(0.12278793, dtype=float32), array(0.12277713, dtype=float32), array(0.12276558, dtype=float32), array(0.12275404, dtype=float32), array(0.12274321, dtype=float32), array(0.12273057, dtype=float32), array(0.12271986, dtype=float32), array(0.12270723, dtype=float32), array(0.12269737, dtype=float32), array(0.12268375, dtype=float32), array(0.12267467, dtype=float32), array(0.12266314, dtype=float32), array(0.12265179, dtype=float32), array(0.1226419, dtype=float32), array(0.12262903, dtype=float32), array(0.12261677, dtype=float32), array(0.12260596, dtype=float32), arra