In [264]:
import torch
from torch.utils.data import DataLoader,Dataset,default_collate,RandomSampler,SequentialSampler,BatchSampler,Sampler
from torch import nn
import numpy as np

In [229]:
class TempDataset(Dataset):
    def __init__(self):
        super(TempDataset, self).__init__()
        pass
    def __getitem__(self,index):
        print("getitem is called",index)
        return index,index*10,index*100
    def __len__(self):
        len=50
        print("len is called ",len)
        return len

In [230]:
class OwnDataLoader:
    def __init__(self, dataset, batch_size=1, shuffle=False, sampler=None,
           batch_sampler=None, num_workers=0, collate_fn=None,
           pin_memory=False, drop_last=False, timeout=0,
           worker_init_fn=None, *, prefetch_factor=2,
           persistent_workers=False):
        pass

    

In [231]:
dataset=TempDataset()
print(dataset)
for i in range(len(dataset)):
    print(dataset[i])

len is called  50
getitem is called 0
(0, 0, 0)
getitem is called 1
(1, 10, 100)
getitem is called 2
(2, 20, 200)
getitem is called 3
(3, 30, 300)
getitem is called 4
(4, 40, 400)
getitem is called 5
(5, 50, 500)
getitem is called 6
(6, 60, 600)
getitem is called 7
(7, 70, 700)
getitem is called 8
(8, 80, 800)
getitem is called 9
(9, 90, 900)
getitem is called 10
(10, 100, 1000)
getitem is called 11
(11, 110, 1100)
getitem is called 12
(12, 120, 1200)
getitem is called 13
(13, 130, 1300)
getitem is called 14
(14, 140, 1400)
getitem is called 15
(15, 150, 1500)
getitem is called 16
(16, 160, 1600)
getitem is called 17
(17, 170, 1700)
getitem is called 18
(18, 180, 1800)
getitem is called 19
(19, 190, 1900)
getitem is called 20
(20, 200, 2000)
getitem is called 21
(21, 210, 2100)
getitem is called 22
(22, 220, 2200)
getitem is called 23
(23, 230, 2300)
getitem is called 24
(24, 240, 2400)
getitem is called 25
(25, 250, 2500)
getitem is called 26
(26, 260, 2600)
getitem is called 27
(27, 

In [263]:
dataload=DataLoader(dataset,sampler=RandomSampler(dataset),drop_last=False)
for i in dataload:
    print(i)
print(len(dataload))

tensor([210])
tensor([90])
tensor([110])
tensor([200])
tensor([330])
tensor([50])
tensor([70])
tensor([190])
tensor([270])
tensor([30])
tensor([150])
tensor([320])
tensor([260])
tensor([170])
tensor([80])
tensor([290])
tensor([250])
tensor([140])
tensor([0])
tensor([180])
tensor([300])
tensor([240])
tensor([130])
tensor([310])
tensor([230])
tensor([100])
tensor([20])
tensor([120])
tensor([220])
tensor([60])
tensor([10])
tensor([160])
tensor([280])
tensor([340])
tensor([40])
35


In [262]:
type(dataload)

torch.utils.data.dataloader.DataLoader

In [233]:
dataload2=DataLoader(dataset)
for i in dataload2:
    print(i)

len is called  50
getitem is called 0
[tensor([0]), tensor([0]), tensor([0])]
getitem is called 1
[tensor([1]), tensor([10]), tensor([100])]
getitem is called 2
[tensor([2]), tensor([20]), tensor([200])]
getitem is called 3
[tensor([3]), tensor([30]), tensor([300])]
getitem is called 4
[tensor([4]), tensor([40]), tensor([400])]
getitem is called 5
[tensor([5]), tensor([50]), tensor([500])]
getitem is called 6
[tensor([6]), tensor([60]), tensor([600])]
getitem is called 7
[tensor([7]), tensor([70]), tensor([700])]
getitem is called 8
[tensor([8]), tensor([80]), tensor([800])]
getitem is called 9
[tensor([9]), tensor([90]), tensor([900])]
getitem is called 10
[tensor([10]), tensor([100]), tensor([1000])]
getitem is called 11
[tensor([11]), tensor([110]), tensor([1100])]
getitem is called 12
[tensor([12]), tensor([120]), tensor([1200])]
getitem is called 13
[tensor([13]), tensor([130]), tensor([1300])]
getitem is called 14
[tensor([14]), tensor([140]), tensor([1400])]
getitem is called 15

In [234]:
dataload3=DataLoader(dataset,batch_size=3,sampler=RandomSampler(dataset))
for i in dataload3:
    print(i)

len is called  50
len is called  50
len is called  50
len is called  50
getitem is called 35
getitem is called 4
getitem is called 41
[tensor([35,  4, 41]), tensor([350,  40, 410]), tensor([3500,  400, 4100])]
getitem is called 5
getitem is called 47
getitem is called 38
[tensor([ 5, 47, 38]), tensor([ 50, 470, 380]), tensor([ 500, 4700, 3800])]
getitem is called 45
getitem is called 14
getitem is called 26
[tensor([45, 14, 26]), tensor([450, 140, 260]), tensor([4500, 1400, 2600])]
getitem is called 1
getitem is called 46
getitem is called 10
[tensor([ 1, 46, 10]), tensor([ 10, 460, 100]), tensor([ 100, 4600, 1000])]
getitem is called 32
getitem is called 34
getitem is called 24
[tensor([32, 34, 24]), tensor([320, 340, 240]), tensor([3200, 3400, 2400])]
getitem is called 42
getitem is called 7
getitem is called 27
[tensor([42,  7, 27]), tensor([420,  70, 270]), tensor([4200,  700, 2700])]
getitem is called 21
getitem is called 12
getitem is called 29
[tensor([21, 12, 29]), tensor([210,

In [235]:
dataload4=DataLoader(dataset,batch_sampler=SequentialSampler(dataset))
print(dataload4)


In [236]:
class Seq_sampler(Sampler):
    def __init__(self,data_set):
        self.data_set=data_set
    def __iter__(self):
        return iter(range(len(dataset)))
    def __len__(self):
        return len(dataset)



In [237]:
import random
iter_obj=list(range(len(dataset)))
# rand=random.randrange(0,len(dataset))
rand=random.shuffle(iter_obj)
print(iter_obj)
# for i in iter_obj:
#     print(iter_obj.count(i))

len is called  50
[19, 30, 1, 9, 33, 25, 40, 38, 12, 0, 39, 48, 46, 24, 45, 44, 28, 8, 23, 5, 3, 36, 11, 31, 13, 7, 14, 17, 49, 47, 21, 27, 32, 26, 6, 35, 43, 10, 34, 41, 42, 22, 2, 4, 20, 29, 18, 16, 37, 15]


In [238]:
import random


class Random_sampler(Sampler):
    def __init__(self,data_set):
        self.data_set=data_set
    def __iter__(self):
        array=np.random.randint(0,len(dataset),(1,len(dataset)-1))
        return array
    def __len__(self):
        return len(dataset)


In [239]:
ran_sample=Random_sampler(dataset)
ran_sample.__iter__()

len is called  50
len is called  50


array([[44, 18,  7, 19,  7, 48, 43, 30, 33, 27, 38, 41,  0,  4, 48, 39,
        23,  0, 27, 47, 35, 22, 34, 42, 45, 21, 16, 12, 28, 16, 19, 43,
        29, 48, 29,  8,  4,  5, 38, 15, 20, 37,  2,  2, 11, 22,  1, 49,
        49]])

In [240]:
dataload5=DataLoader(dataset,batch_size=2,sampler=RandomSampler(dataset),collate_fn=default_collate)
for i in dataload5:
    print(i)

len is called  50
len is called  50
len is called  50
len is called  50
getitem is called 17
getitem is called 47
[tensor([17, 47]), tensor([170, 470]), tensor([1700, 4700])]
getitem is called 12
getitem is called 6
[tensor([12,  6]), tensor([120,  60]), tensor([1200,  600])]
getitem is called 5
getitem is called 22
[tensor([ 5, 22]), tensor([ 50, 220]), tensor([ 500, 2200])]
getitem is called 18
getitem is called 30
[tensor([18, 30]), tensor([180, 300]), tensor([1800, 3000])]
getitem is called 41
getitem is called 29
[tensor([41, 29]), tensor([410, 290]), tensor([4100, 2900])]
getitem is called 32
getitem is called 4
[tensor([32,  4]), tensor([320,  40]), tensor([3200,  400])]
getitem is called 13
getitem is called 44
[tensor([13, 44]), tensor([130, 440]), tensor([1300, 4400])]
getitem is called 49
getitem is called 38
[tensor([49, 38]), tensor([490, 380]), tensor([4900, 3800])]
getitem is called 7
getitem is called 36
[tensor([ 7, 36]), tensor([ 70, 360]), tensor([ 700, 3600])]
getit

In [241]:
def collate(dataset):
    data=[]
    for i in range(len(dataset)):
        x,y,z=dataset.__getitem__(i)
        data.append(tuple([x,y,z]))
    return data


In [242]:
collate(dataset)

len is called  50
getitem is called 0
getitem is called 1
getitem is called 2
getitem is called 3
getitem is called 4
getitem is called 5
getitem is called 6
getitem is called 7
getitem is called 8
getitem is called 9
getitem is called 10
getitem is called 11
getitem is called 12
getitem is called 13
getitem is called 14
getitem is called 15
getitem is called 16
getitem is called 17
getitem is called 18
getitem is called 19
getitem is called 20
getitem is called 21
getitem is called 22
getitem is called 23
getitem is called 24
getitem is called 25
getitem is called 26
getitem is called 27
getitem is called 28
getitem is called 29
getitem is called 30
getitem is called 31
getitem is called 32
getitem is called 33
getitem is called 34
getitem is called 35
getitem is called 36
getitem is called 37
getitem is called 38
getitem is called 39
getitem is called 40
getitem is called 41
getitem is called 42
getitem is called 43
getitem is called 44
getitem is called 45
getitem is called 46
getit

[(0, 0, 0),
 (1, 10, 100),
 (2, 20, 200),
 (3, 30, 300),
 (4, 40, 400),
 (5, 50, 500),
 (6, 60, 600),
 (7, 70, 700),
 (8, 80, 800),
 (9, 90, 900),
 (10, 100, 1000),
 (11, 110, 1100),
 (12, 120, 1200),
 (13, 130, 1300),
 (14, 140, 1400),
 (15, 150, 1500),
 (16, 160, 1600),
 (17, 170, 1700),
 (18, 180, 1800),
 (19, 190, 1900),
 (20, 200, 2000),
 (21, 210, 2100),
 (22, 220, 2200),
 (23, 230, 2300),
 (24, 240, 2400),
 (25, 250, 2500),
 (26, 260, 2600),
 (27, 270, 2700),
 (28, 280, 2800),
 (29, 290, 2900),
 (30, 300, 3000),
 (31, 310, 3100),
 (32, 320, 3200),
 (33, 330, 3300),
 (34, 340, 3400),
 (35, 350, 3500),
 (36, 360, 3600),
 (37, 370, 3700),
 (38, 380, 3800),
 (39, 390, 3900),
 (40, 400, 4000),
 (41, 410, 4100),
 (42, 420, 4200),
 (43, 430, 4300),
 (44, 440, 4400),
 (45, 450, 4500),
 (46, 460, 4600),
 (47, 470, 4700),
 (48, 480, 4800),
 (49, 490, 4900)]

In [243]:
dataload5=DataLoader(dataset,batch_size=3,collate_fn=default_collate)
for i in dataload5:
    print(i)

len is called  50
getitem is called 0
getitem is called 1
getitem is called 2
[tensor([0, 1, 2]), tensor([ 0, 10, 20]), tensor([  0, 100, 200])]
getitem is called 3
getitem is called 4
getitem is called 5
[tensor([3, 4, 5]), tensor([30, 40, 50]), tensor([300, 400, 500])]
getitem is called 6
getitem is called 7
getitem is called 8
[tensor([6, 7, 8]), tensor([60, 70, 80]), tensor([600, 700, 800])]
getitem is called 9
getitem is called 10
getitem is called 11
[tensor([ 9, 10, 11]), tensor([ 90, 100, 110]), tensor([ 900, 1000, 1100])]
getitem is called 12
getitem is called 13
getitem is called 14
[tensor([12, 13, 14]), tensor([120, 130, 140]), tensor([1200, 1300, 1400])]
getitem is called 15
getitem is called 16
getitem is called 17
[tensor([15, 16, 17]), tensor([150, 160, 170]), tensor([1500, 1600, 1700])]
getitem is called 18
getitem is called 19
getitem is called 20
[tensor([18, 19, 20]), tensor([180, 190, 200]), tensor([1800, 1900, 2000])]
getitem is called 21
getitem is called 22
geti

In [244]:
dataload5=DataLoader(dataset,batch_size=3,num_workers=2,prefetch_factor=4)
for i in dataload5:
    print(i)

getitem is called getitem is called0 
3getitem is called 
getitem is called1len is called  50
 
4
getitem is calledgetitem is called  2
5
getitem is called getitem is called6
 9getitem is called
 getitem is called7 10

getitem is calledgetitem is called  8
getitem is called 12
11getitem is called
 getitem is called13
getitem is called 14 15
[tensor([0, 1, 2]), tensor([ 0, 10, 20]), tensor([  0, 100, 200])]
[tensor([3, 4, 5]), tensor([30, 40, 50]), tensor([300, 400, 500])]
[tensor([6, 7, 8]), tensor([60, 70, 80]), tensor([600, 700, 800])]
[tensor([ 9, 10, 11]), tensor([ 90, 100, 110]), tensor([ 900, 1000, 1100])]
getitem is called 
16getitem is called 18
getitem is called 19
getitem is called 
20getitem is called
 getitem is called17 
24getitem is called
 getitem is called 25
getitem is called 2621

getitem is calledgetitem is called 30
getitem is called 31
getitem is called  3222

getitem is calledgetitem is called  2336

getitem is called getitem is called37
 getitem is called27
 geti

In [245]:
dataload5=DataLoader(dataset,num_workers=2,prefetch_factor=2)
for i in dataload5:
    print(i)

getitem is called 0
getitem is called getitem is called 1
getitem is called2
 3getitem is called
 4getitem is called
 5
getitem is called 6
getitem is called 7getitem is called
 8len is called  50
[tensor([0]), tensor([0]), tensor([0])]
[tensor([1]), tensor([10]), tensor([100])]
[tensor([2]), tensor([20]), tensor([200])]
[tensor([3]), tensor([30]), tensor([300])]
[tensor([4]), tensor([40]), tensor([400])]

getitem is called 9
getitem is called 10
getitem is called 11
getitem is called 12
getitem is called 13

getitem is called 14getitem is called 15getitem is called 16

getitem is called 17
getitem is called 18
getitem is called 19
getitem is called getitem is called21 
20
getitem is called 22
getitem is called 23
getitem is calledgetitem is called 24
 getitem is called25
 26
getitem is called 27
getitem is calledgetitem is called  2829[tensor([5]), tensor([50]), tensor([500])]
[tensor([6]), tensor([60]), tensor([600])]
[tensor([7]), tensor([70]), tensor([700])]
[tensor([8]), tensor([8

In [246]:
dataload5=DataLoader(dataset,sampler=RandomSampler(dataset),num_workers=2,prefetch_factor=2)
for i in dataload5:
    print(i)

len is called  50
len is called  50
len is called  50
len is called  50
getitem is called 48
getitem is called 42getitem is called
 39getitem is called 
16getitem is called
 44
getitem is called 18
getitem is called 17
getitem is called 46
getitem is called[tensor([48]), tensor([480]), tensor([4800])]
[tensor([42]), tensor([420]), tensor([4200])]
[tensor([39]), tensor([390]), tensor([3900])]
[tensor([16]), tensor([160]), tensor([1600])]
[tensor([44]), tensor([440]), tensor([4400])]
 33
getitem is called 49getitem is called 
getitem is called 343

getitem is called 2
 getitem is called22getitem is called 
40
getitem is called 30
getitem is called getitem is called9 
20getitem is called
getitem is called 29
 36
getitem is called 10getitem is called
 21
getitem is called 35
getitem is called 4
[tensor([18]), tensor([180]), tensor([1800])]
[tensor([17]), tensor([170]), tensor([1700])]
[tensor([46]), tensor([460]), tensor([4600])]
[tensor([33]), tensor([330]), tensor([3300])]
[tensor([49]),

In [247]:
dataload5=DataLoader(dataset,batch_size=2,sampler=SequentialSampler(dataset))
for i in dataload5:
    print(i)

len is called  50
getitem is called 0
getitem is called 1
[tensor([0, 1]), tensor([ 0, 10]), tensor([  0, 100])]
getitem is called 2
getitem is called 3
[tensor([2, 3]), tensor([20, 30]), tensor([200, 300])]
getitem is called 4
getitem is called 5
[tensor([4, 5]), tensor([40, 50]), tensor([400, 500])]
getitem is called 6
getitem is called 7
[tensor([6, 7]), tensor([60, 70]), tensor([600, 700])]
getitem is called 8
getitem is called 9
[tensor([8, 9]), tensor([80, 90]), tensor([800, 900])]
getitem is called 10
getitem is called 11
[tensor([10, 11]), tensor([100, 110]), tensor([1000, 1100])]
getitem is called 12
getitem is called 13
[tensor([12, 13]), tensor([120, 130]), tensor([1200, 1300])]
getitem is called 14
getitem is called 15
[tensor([14, 15]), tensor([140, 150]), tensor([1400, 1500])]
getitem is called 16
getitem is called 17
[tensor([16, 17]), tensor([160, 170]), tensor([1600, 1700])]
getitem is called 18
getitem is called 19
[tensor([18, 19]), tensor([180, 190]), tensor([1800, 

In [248]:
count =0 
for data in dataset:
    print(data)
    count+=1
    if count>100:
        break

getitem is called 0
(0, 0, 0)
getitem is called 1
(1, 10, 100)
getitem is called 2
(2, 20, 200)
getitem is called 3
(3, 30, 300)
getitem is called 4
(4, 40, 400)
getitem is called 5
(5, 50, 500)
getitem is called 6
(6, 60, 600)
getitem is called 7
(7, 70, 700)
getitem is called 8
(8, 80, 800)
getitem is called 9
(9, 90, 900)
getitem is called 10
(10, 100, 1000)
getitem is called 11
(11, 110, 1100)
getitem is called 12
(12, 120, 1200)
getitem is called 13
(13, 130, 1300)
getitem is called 14
(14, 140, 1400)
getitem is called 15
(15, 150, 1500)
getitem is called 16
(16, 160, 1600)
getitem is called 17
(17, 170, 1700)
getitem is called 18
(18, 180, 1800)
getitem is called 19
(19, 190, 1900)
getitem is called 20
(20, 200, 2000)
getitem is called 21
(21, 210, 2100)
getitem is called 22
(22, 220, 2200)
getitem is called 23
(23, 230, 2300)
getitem is called 24
(24, 240, 2400)
getitem is called 25
(25, 250, 2500)
getitem is called 26
(26, 260, 2600)
getitem is called 27
(27, 270, 2700)
getitem

In [249]:
dataset=np.arange(0,35,1)*10
print(dataset)
sample=RandomSampler(dataset)
print(sample)
obj=iter(sample)

[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340]


In [250]:

drop_last=1
batch_size=6

obj=iter(sample)
n=len(sample)
count=0


for i in range(n//batch_size):
    a=[]
    for i in range(batch_size):
        a.append(dataset[next(obj)])
    count+=1
    print(a)

if not drop_last:
    a=[]
    for i in range(n-count*batch_size):
        a.append(dataset[next(obj)])
    print(a)
# print("Count",count)



[10, 250, 30, 340, 50, 190]
[260, 240, 290, 170, 320, 160]
[330, 100, 60, 200, 220, 270]
[280, 300, 70, 150, 310, 120]
[40, 110, 20, 90, 180, 140]


In [273]:
batch_sampler=BatchSampler(sampler=RandomSampler(dataset),batch_size=2,drop_last=False)
dataloader=DataLoader(dataset,batch_sampler=batch_sampler)
for i in dataloader:
    print(i)

tensor([260, 100])
tensor([270,  70])
tensor([280, 230])
tensor([180, 210])
tensor([320, 340])
tensor([330,   0])
tensor([60, 20])
tensor([240, 110])
tensor([80, 40])
tensor([160, 170])
tensor([220, 250])
tensor([50, 90])
tensor([ 10, 150])
tensor([200, 140])
tensor([300,  30])
tensor([290, 120])
tensor([190, 130])
tensor([310])


In [251]:
obj=iter(sample)
print(next(obj))

5
